---
## Graylog server options
Yeebase:
  Graylog:
#    host: '127.0.0.1'
#    port: 12201
#    chunksize: 'wan'
#    skipStatusCodes: [403, 404]
#
    Logger:
      backend: Yeebase\Graylog\Log\Backend\GraylogBackend
      backendOptions:
        severityThreshold: '%LOG_INFO%'
        logIpAddress: true
        alsoLogWithSystemLogger: false

## Optional: Register GraylogExceptionHandler
#Neos:
#  Flow:
#    error:
#      exceptionHandler:
#        className: 'Yeebase\Graylog\Error\GraylogExceptionHandler'
